// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package networkmonitor_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/isometry/terraform-provider-faws/internal/acctest/statecheck"
	tfnetworkmonitor "github.com/isometry/terraform-provider-faws/internal/service/networkmonitor"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfnetworkmonitor.ServicePackage(context.Background()), resourceAddress, knownValue)
}
