// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package amplify_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/isometry/terraform-provider-faws/internal/acctest/statecheck"
	tfamplify "github.com/isometry/terraform-provider-faws/internal/service/amplify"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfamplify.ServicePackage(context.Background()), resourceAddress, knownValue)
}
